#pragma once
// Historical x86 evidence only. Native fields/allocators are checked separately.
static_assert(sizeof(InitialData) == 48 && sizeof(ActorRecord) == 0x220);
static_assert(sizeof(ControlRecord) == 16 && sizeof(ControlTable) == 12);
static_assert(sizeof(AnimationRecord) == 48 && sizeof(FrameRecord) == 248);
static_assert(sizeof(FrameAppearance) == 28 && offsetof(FrameAppearance, color) == 4);
static_assert(offsetof(FrameRecord, vertices) == 8 && offsetof(FrameRecord, base_positions) == 128);
static_assert(offsetof(FrameRecord, positions) == 176 && offsetof(FrameRecord, pivot_x) == 236);
static_assert(offsetof(CameraBoundsRecord, x) == 40 && offsetof(CameraBoundsRecord, bounds) == 72);
static_assert(sizeof(ManagerPrefix) == 136);
static_assert(sizeof(RenderLayerRecord) == 20 && offsetof(RenderLayerRecord, begin) == 12);
static_assert(offsetof(ManagerPrefix, pool) == 4 && offsetof(ManagerPrefix, owner_list) == 8);
static_assert(offsetof(ManagerPrefix, render_layers) == 20 && offsetof(ManagerPrefix, update_mask) == 64);
static_assert(offsetof(ActorRecord, pool_handle) == 12 && offsetof(ActorRecord, priority_entry) == 16);
static_assert(offsetof(ActorRecord, spawn_x) == 80 && offsetof(ActorRecord, update_vm) == 92);
static_assert(offsetof(ActorRecord, rotation) == 164 && offsetof(ActorRecord, blend) == 196);
#define KINOKO_ACTOR_FIELD(T, M, O) static_assert(offsetof(T, M) == O)
KINOKO_ACTOR_FIELD(ActorRecord, owner_references, 8);
KINOKO_ACTOR_FIELD(ActorRecord, registration_flag20, 20);
KINOKO_ACTOR_FIELD(ActorRecord, active, 40);
KINOKO_ACTOR_FIELD(ActorRecord, update_group, 232);
KINOKO_ACTOR_FIELD(ActorRecord, collision_group, 312);
KINOKO_ACTOR_FIELD(ActorRecord, collision_mask, 316);
KINOKO_ACTOR_FIELD(ActorRecord, collision_index, 336);
KINOKO_ACTOR_FIELD(ActorRecord, collision_scan_cache, 480);
KINOKO_ACTOR_FIELD(ActorRecord, release_pending, 22);
KINOKO_ACTOR_FIELD(ActorRecord, owner, 24);
KINOKO_ACTOR_FIELD(ActorRecord, owner_control, 28);
KINOKO_ACTOR_FIELD(ActorRecord, step, 32);
KINOKO_ACTOR_FIELD(ActorRecord, step_control, 36);
KINOKO_ACTOR_FIELD(ActorRecord, script_object, 44);
KINOKO_ACTOR_FIELD(ActorRecord, initial_function, 56);
KINOKO_ACTOR_FIELD(ActorRecord, initial_argument, 68);
KINOKO_ACTOR_FIELD(ActorRecord, update_environment, 96);
KINOKO_ACTOR_FIELD(ActorRecord, update_function, 108);
KINOKO_ACTOR_FIELD(ActorRecord, collision_environment, 124);
KINOKO_ACTOR_FIELD(ActorRecord, collision_function, 136);
KINOKO_ACTOR_FIELD(ActorRecord, manager, 148);
KINOKO_ACTOR_FIELD(ActorRecord, sprite_frame, 152);
KINOKO_ACTOR_FIELD(ActorRecord, scale, 168);
KINOKO_ACTOR_FIELD(ActorRecord, animation, 200);
KINOKO_ACTOR_FIELD(ActorRecord, frame_time, 216);
KINOKO_ACTOR_FIELD(ActorRecord, priority, 228);
KINOKO_ACTOR_FIELD(ActorRecord, x, 240);
KINOKO_ACTOR_FIELD(ActorRecord, previous_x, 248);
KINOKO_ACTOR_FIELD(ActorRecord, previous_y, 252);
KINOKO_ACTOR_FIELD(ActorRecord, velocity_x, 256);
KINOKO_ACTOR_FIELD(ActorRecord, parent_velocity_y, 268);
KINOKO_ACTOR_FIELD(ActorRecord, pitch, 276);
KINOKO_ACTOR_FIELD(ActorRecord, hits, 284);
KINOKO_ACTOR_FIELD(ActorRecord, crushed, 300);
KINOKO_ACTOR_FIELD(ActorRecord, free_width, 304);
KINOKO_ACTOR_FIELD(ActorRecord, free_height, 308);
KINOKO_ACTOR_FIELD(ActorRecord, collision_vm, 120);
KINOKO_ACTOR_FIELD(ActorRecord, direction, 272);
KINOKO_ACTOR_FIELD(ActorRecord, collision_chip, 328);
KINOKO_ACTOR_FIELD(ActorRecord, collision_placement, 332);
KINOKO_ACTOR_FIELD(ActorRecord, inline_slots, 340);
KINOKO_ACTOR_FIELD(ActorRecord, bounds_anchor_x, 352);
KINOKO_ACTOR_FIELD(ActorRecord, initial, 376);
KINOKO_ACTOR_FIELD(InitialData, width, 12);
KINOKO_ACTOR_FIELD(InitialData, chip_flags, 16);
KINOKO_ACTOR_FIELD(InitialData, chip_bound_type, 34);
KINOKO_ACTOR_FIELD(ActorRecord, local_bounds, 424);
KINOKO_ACTOR_FIELD(ActorRecord, world_bounds, 440);
KINOKO_ACTOR_FIELD(ActorRecord, chip_cache_storage, 512);
KINOKO_ACTOR_FIELD(AnimationRecord, loops, 24);
KINOKO_ACTOR_FIELD(AnimationRecord, frames_begin, 8);
KINOKO_ACTOR_FIELD(AnimationRecord, frames_capacity, 16);
KINOKO_ACTOR_FIELD(AnimationRecord, duration_total, 44);
KINOKO_ACTOR_FIELD(AnimationRecord, left, 28);
KINOKO_ACTOR_FIELD(FrameRecord, duration, 240);
KINOKO_ACTOR_FIELD(FrameRecord, owned_payload, 244);
KINOKO_ACTOR_FIELD(ManagerPrefix, animation_lookup, 36);
KINOKO_ACTOR_FIELD(ManagerPrefix, animations, 52);
KINOKO_ACTOR_FIELD(ManagerPrefix, textures, 68);
KINOKO_ACTOR_FIELD(ManagerPrefix, actors, 84);
KINOKO_ACTOR_FIELD(ManagerPrefix, iteration, 100);
KINOKO_ACTOR_FIELD(ManagerPrefix, iteration_count, 116);
KINOKO_ACTOR_FIELD(ManagerPrefix, cleanup_pending, 120);
KINOKO_ACTOR_FIELD(ManagerPrefix, callback_candidates, 124);
#undef KINOKO_ACTOR_FIELD
