#pragma once
#include <cstdint>
#include <windows.h>
#ifndef KINOKO_GPU_GAME
#include <d3d9.h>
#endif
namespace kinoko::graphics {
// State values preserve the original game command vocabulary. These are not
// SDK objects or serialized records. Only the native comparison backend aliases
// SDK types; the SDL GPU backend owns its runtime descriptions.
#ifdef KINOKO_GPU_GAME
using Color=std::uint32_t;
using Format=std::uint32_t;
using Pool=std::uint32_t;
using DeviceKind=std::uint32_t;
using Primitive=std::uint32_t;
using RenderState=std::uint32_t;
using SamplerState=std::uint32_t;
using TextureStageState=std::uint32_t;
using Transform=std::uint32_t;
struct Capabilities {std::uint32_t TextureCaps=0,MaxTextureWidth=0,MaxTextureHeight=0;};
struct Presentation {
    UINT BackBufferWidth=0,BackBufferHeight=0; Format BackBufferFormat=0;
    UINT BackBufferCount=0; std::uint32_t MultiSampleType=0,MultiSampleQuality=0,SwapEffect=0;
    HWND hDeviceWindow=nullptr; BOOL Windowed=FALSE,EnableAutoDepthStencil=FALSE;
    Format AutoDepthStencilFormat=0; DWORD Flags=0;
    UINT FullScreen_RefreshRateInHz=0,PresentationInterval=0;
};
struct DisplayMode {UINT Width,Height,RefreshRate;graphics::Format Format;};
struct SurfaceDescription {
    graphics::Format Format;std::uint32_t Type;DWORD Usage;graphics::Pool Pool;
    std::uint32_t MultiSampleType;DWORD MultiSampleQuality;UINT Width,Height;
};
struct MappedPixels {INT Pitch;void* pBits;};
struct Matrix {float m[4][4];};
struct ClearRect {LONG x1,y1,x2,y2;};
struct VertexElement {std::uint16_t Stream,Offset;std::uint8_t Type,Method,Usage,UsageIndex;};
static_assert(sizeof(Matrix)==64 && sizeof(VertexElement)==8);
inline constexpr std::uint32_t adapter_default=static_cast<std::uint32_t>(0x0u);
inline constexpr std::uint32_t blend_operation_add=static_cast<std::uint32_t>(0x1u);
inline constexpr std::uint32_t blend_operation_revsubtract=static_cast<std::uint32_t>(0x3u);
inline constexpr std::uint32_t blend_destcolor=static_cast<std::uint32_t>(0x9u);
inline constexpr std::uint32_t blend_invsrcalpha=static_cast<std::uint32_t>(0x6u);
inline constexpr std::uint32_t blend_one=static_cast<std::uint32_t>(0x2u);
inline constexpr std::uint32_t blend_srcalpha=static_cast<std::uint32_t>(0x5u);
inline constexpr std::uint32_t blend_srccolor=static_cast<std::uint32_t>(0x3u);
inline constexpr std::uint32_t blend_zero=static_cast<std::uint32_t>(0x1u);
inline constexpr std::uint32_t clear_stencil=static_cast<std::uint32_t>(0x4u);
inline constexpr std::uint32_t clear_target=static_cast<std::uint32_t>(0x1u);
inline constexpr std::uint32_t clear_zbuffer=static_cast<std::uint32_t>(0x2u);
inline constexpr std::uint32_t compare_always=static_cast<std::uint32_t>(0x8u);
inline constexpr std::uint32_t compare_lessequal=static_cast<std::uint32_t>(0x4u);
inline constexpr std::uint32_t creation_hardware_vertexprocessing=static_cast<std::uint32_t>(0x40u);
inline constexpr std::uint32_t creation_multithreaded=static_cast<std::uint32_t>(0x4u);
inline constexpr std::uint32_t creation_software_vertexprocessing=static_cast<std::uint32_t>(0x20u);
inline constexpr std::uint32_t cull_ccw=static_cast<std::uint32_t>(0x3u);
inline constexpr std::uint32_t cull_cw=static_cast<std::uint32_t>(0x2u);
inline constexpr std::uint32_t cull_none=static_cast<std::uint32_t>(0x1u);
inline constexpr std::uint32_t declaration_method_default=static_cast<std::uint32_t>(0x0u);
inline constexpr std::uint32_t element_float2=static_cast<std::uint32_t>(0x1u);
inline constexpr std::uint32_t element_float3=static_cast<std::uint32_t>(0x2u);
inline constexpr std::uint32_t semantic_normal=static_cast<std::uint32_t>(0x3u);
inline constexpr std::uint32_t semantic_position=static_cast<std::uint32_t>(0x0u);
inline constexpr std::uint32_t semantic_texcoord=static_cast<std::uint32_t>(0x5u);
inline constexpr std::uint32_t device_hal=static_cast<std::uint32_t>(0x1u);
inline constexpr std::uint32_t device_ref=static_cast<std::uint32_t>(0x2u);
inline constexpr HRESULT error_devicelost=static_cast<HRESULT>(0x88760868u);
inline constexpr HRESULT error_devicenotreset=static_cast<HRESULT>(0x88760869u);
inline constexpr HRESULT error_invalidcall=static_cast<HRESULT>(0x8876086cu);
inline constexpr HRESULT error_wasstilldrawing=static_cast<HRESULT>(0x8876021cu);
inline constexpr std::uint32_t fill_solid=static_cast<std::uint32_t>(0x3u);
inline constexpr std::uint32_t format_a1r5g5b5=static_cast<std::uint32_t>(0x19u);
inline constexpr std::uint32_t format_a8r8g8b8=static_cast<std::uint32_t>(0x15u);
inline constexpr std::uint32_t format_d24s8=static_cast<std::uint32_t>(0x4bu);
inline constexpr std::uint32_t format_index16=static_cast<std::uint32_t>(0x65u);
inline constexpr std::uint32_t format_x8r8g8b8=static_cast<std::uint32_t>(0x16u);
inline constexpr std::uint32_t vertex_diffuse=static_cast<std::uint32_t>(0x40u);
inline constexpr std::uint32_t vertex_normal=static_cast<std::uint32_t>(0x10u);
inline constexpr std::uint32_t vertex_tex1=static_cast<std::uint32_t>(0x100u);
inline constexpr std::uint32_t vertex_xyz=static_cast<std::uint32_t>(0x2u);
inline constexpr std::uint32_t vertex_xyzrhw=static_cast<std::uint32_t>(0x4u);
inline constexpr std::uint32_t multisample_none=static_cast<std::uint32_t>(0x0u);
inline constexpr std::uint32_t pool_default=static_cast<std::uint32_t>(0x0u);
inline constexpr std::uint32_t pool_managed=static_cast<std::uint32_t>(0x1u);
inline constexpr std::uint32_t presentation_flag_discard_depthstencil=static_cast<std::uint32_t>(0x2u);
inline constexpr std::uint32_t presentation_donotwait=static_cast<std::uint32_t>(0x1u);
inline constexpr std::uint32_t presentation_interval_one=static_cast<std::uint32_t>(0x1u);
inline constexpr std::uint32_t texture_caps_squareonly=static_cast<std::uint32_t>(0x20u);
inline constexpr std::uint32_t primitive_trianglelist=static_cast<std::uint32_t>(0x4u);
inline constexpr std::uint32_t primitive_trianglestrip=static_cast<std::uint32_t>(0x5u);
inline constexpr std::uint32_t state_alphablendenable=static_cast<std::uint32_t>(0x1bu);
inline constexpr std::uint32_t state_alphafunc=static_cast<std::uint32_t>(0x19u);
inline constexpr std::uint32_t state_alpharef=static_cast<std::uint32_t>(0x18u);
inline constexpr std::uint32_t state_alphatestenable=static_cast<std::uint32_t>(0xfu);
inline constexpr std::uint32_t state_blendop=static_cast<std::uint32_t>(0xabu);
inline constexpr std::uint32_t state_cullmode=static_cast<std::uint32_t>(0x16u);
inline constexpr std::uint32_t state_destblend=static_cast<std::uint32_t>(0x14u);
inline constexpr std::uint32_t state_fillmode=static_cast<std::uint32_t>(0x8u);
inline constexpr std::uint32_t state_lighting=static_cast<std::uint32_t>(0x89u);
inline constexpr std::uint32_t state_srcblend=static_cast<std::uint32_t>(0x13u);
inline constexpr std::uint32_t state_stencilmask=static_cast<std::uint32_t>(0x3au);
inline constexpr std::uint32_t state_zenable=static_cast<std::uint32_t>(0x7u);
inline constexpr std::uint32_t state_zfunc=static_cast<std::uint32_t>(0x17u);
inline constexpr std::uint32_t state_zwriteenable=static_cast<std::uint32_t>(0xeu);
inline constexpr std::uint32_t resource_surface=static_cast<std::uint32_t>(0x1u);
inline constexpr std::uint32_t sampler_addressu=static_cast<std::uint32_t>(0x1u);
inline constexpr std::uint32_t sampler_addressv=static_cast<std::uint32_t>(0x2u);
inline constexpr std::uint32_t sampler_magfilter=static_cast<std::uint32_t>(0x5u);
inline constexpr std::uint32_t sampler_minfilter=static_cast<std::uint32_t>(0x6u);
inline constexpr std::uint32_t sampler_mipfilter=static_cast<std::uint32_t>(0x7u);
inline constexpr std::uint32_t swap_discard=static_cast<std::uint32_t>(0x1u);
inline constexpr std::uint32_t address_clamp=static_cast<std::uint32_t>(0x3u);
inline constexpr std::uint32_t address_wrap=static_cast<std::uint32_t>(0x1u);
inline constexpr std::uint32_t filter_linear=static_cast<std::uint32_t>(0x2u);
inline constexpr std::uint32_t filter_point=static_cast<std::uint32_t>(0x1u);
inline constexpr std::uint32_t texture_operation_modulate=static_cast<std::uint32_t>(0x4u);
inline constexpr std::uint32_t texture_stage_alphaop=static_cast<std::uint32_t>(0x4u);
inline constexpr std::uint32_t transform_projection=static_cast<std::uint32_t>(0x3u);
inline constexpr std::uint32_t transform_view=static_cast<std::uint32_t>(0x2u);
inline constexpr std::uint32_t transform_world=static_cast<std::uint32_t>(0x100u);
inline constexpr std::uint32_t usage_rendertarget=static_cast<std::uint32_t>(0x1u);
inline constexpr HRESULT ok=static_cast<HRESULT>(0x0u);
inline constexpr std::uint32_t sdk_version=static_cast<std::uint32_t>(0x20u);
constexpr VertexElement declaration_end(){return {0xff,0,17,0,0,0};}
#else
using Capabilities=::D3DCAPS9;
using Presentation=::D3DPRESENT_PARAMETERS;
using DisplayMode=::D3DDISPLAYMODE;
using SurfaceDescription=::D3DSURFACE_DESC;
using MappedPixels=::D3DLOCKED_RECT;
using Matrix=::D3DMATRIX;
using ClearRect=::D3DRECT;
using VertexElement=::D3DVERTEXELEMENT9;
using Color=::D3DCOLOR;
using Format=::D3DFORMAT;
using Pool=::D3DPOOL;
using DeviceKind=::D3DDEVTYPE;
using Primitive=::D3DPRIMITIVETYPE;
using RenderState=::D3DRENDERSTATETYPE;
using SamplerState=::D3DSAMPLERSTATETYPE;
using TextureStageState=::D3DTEXTURESTAGESTATETYPE;
using Transform=::D3DTRANSFORMSTATETYPE;
inline constexpr auto adapter_default=D3DADAPTER_DEFAULT;
inline constexpr auto blend_operation_add=D3DBLENDOP_ADD;
inline constexpr auto blend_operation_revsubtract=D3DBLENDOP_REVSUBTRACT;
inline constexpr auto blend_destcolor=D3DBLEND_DESTCOLOR;
inline constexpr auto blend_invsrcalpha=D3DBLEND_INVSRCALPHA;
inline constexpr auto blend_one=D3DBLEND_ONE;
inline constexpr auto blend_srcalpha=D3DBLEND_SRCALPHA;
inline constexpr auto blend_srccolor=D3DBLEND_SRCCOLOR;
inline constexpr auto blend_zero=D3DBLEND_ZERO;
inline constexpr auto clear_stencil=D3DCLEAR_STENCIL;
inline constexpr auto clear_target=D3DCLEAR_TARGET;
inline constexpr auto clear_zbuffer=D3DCLEAR_ZBUFFER;
inline constexpr auto compare_always=D3DCMP_ALWAYS;
inline constexpr auto compare_lessequal=D3DCMP_LESSEQUAL;
inline constexpr auto creation_hardware_vertexprocessing=D3DCREATE_HARDWARE_VERTEXPROCESSING;
inline constexpr auto creation_multithreaded=D3DCREATE_MULTITHREADED;
inline constexpr auto creation_software_vertexprocessing=D3DCREATE_SOFTWARE_VERTEXPROCESSING;
inline constexpr auto cull_ccw=D3DCULL_CCW;
inline constexpr auto cull_cw=D3DCULL_CW;
inline constexpr auto cull_none=D3DCULL_NONE;
inline constexpr auto declaration_method_default=D3DDECLMETHOD_DEFAULT;
inline constexpr auto element_float2=D3DDECLTYPE_FLOAT2;
inline constexpr auto element_float3=D3DDECLTYPE_FLOAT3;
inline constexpr auto semantic_normal=D3DDECLUSAGE_NORMAL;
inline constexpr auto semantic_position=D3DDECLUSAGE_POSITION;
inline constexpr auto semantic_texcoord=D3DDECLUSAGE_TEXCOORD;
inline constexpr auto device_hal=D3DDEVTYPE_HAL;
inline constexpr auto device_ref=D3DDEVTYPE_REF;
inline constexpr auto error_devicelost=D3DERR_DEVICELOST;
inline constexpr auto error_devicenotreset=D3DERR_DEVICENOTRESET;
inline constexpr auto error_invalidcall=D3DERR_INVALIDCALL;
inline constexpr auto error_wasstilldrawing=D3DERR_WASSTILLDRAWING;
inline constexpr auto fill_solid=D3DFILL_SOLID;
inline constexpr auto format_a1r5g5b5=D3DFMT_A1R5G5B5;
inline constexpr auto format_a8r8g8b8=D3DFMT_A8R8G8B8;
inline constexpr auto format_d24s8=D3DFMT_D24S8;
inline constexpr auto format_index16=D3DFMT_INDEX16;
inline constexpr auto format_x8r8g8b8=D3DFMT_X8R8G8B8;
inline constexpr auto vertex_diffuse=D3DFVF_DIFFUSE;
inline constexpr auto vertex_normal=D3DFVF_NORMAL;
inline constexpr auto vertex_tex1=D3DFVF_TEX1;
inline constexpr auto vertex_xyz=D3DFVF_XYZ;
inline constexpr auto vertex_xyzrhw=D3DFVF_XYZRHW;
inline constexpr auto multisample_none=D3DMULTISAMPLE_NONE;
inline constexpr auto pool_default=D3DPOOL_DEFAULT;
inline constexpr auto pool_managed=D3DPOOL_MANAGED;
inline constexpr auto presentation_flag_discard_depthstencil=D3DPRESENTFLAG_DISCARD_DEPTHSTENCIL;
inline constexpr auto presentation_donotwait=D3DPRESENT_DONOTWAIT;
inline constexpr auto presentation_interval_one=D3DPRESENT_INTERVAL_ONE;
inline constexpr auto texture_caps_squareonly=D3DPTEXTURECAPS_SQUAREONLY;
inline constexpr auto primitive_trianglelist=D3DPT_TRIANGLELIST;
inline constexpr auto primitive_trianglestrip=D3DPT_TRIANGLESTRIP;
inline constexpr auto state_alphablendenable=D3DRS_ALPHABLENDENABLE;
inline constexpr auto state_alphafunc=D3DRS_ALPHAFUNC;
inline constexpr auto state_alpharef=D3DRS_ALPHAREF;
inline constexpr auto state_alphatestenable=D3DRS_ALPHATESTENABLE;
inline constexpr auto state_blendop=D3DRS_BLENDOP;
inline constexpr auto state_cullmode=D3DRS_CULLMODE;
inline constexpr auto state_destblend=D3DRS_DESTBLEND;
inline constexpr auto state_fillmode=D3DRS_FILLMODE;
inline constexpr auto state_lighting=D3DRS_LIGHTING;
inline constexpr auto state_srcblend=D3DRS_SRCBLEND;
inline constexpr auto state_stencilmask=D3DRS_STENCILMASK;
inline constexpr auto state_zenable=D3DRS_ZENABLE;
inline constexpr auto state_zfunc=D3DRS_ZFUNC;
inline constexpr auto state_zwriteenable=D3DRS_ZWRITEENABLE;
inline constexpr auto resource_surface=D3DRTYPE_SURFACE;
inline constexpr auto sampler_addressu=D3DSAMP_ADDRESSU;
inline constexpr auto sampler_addressv=D3DSAMP_ADDRESSV;
inline constexpr auto sampler_magfilter=D3DSAMP_MAGFILTER;
inline constexpr auto sampler_minfilter=D3DSAMP_MINFILTER;
inline constexpr auto sampler_mipfilter=D3DSAMP_MIPFILTER;
inline constexpr auto swap_discard=D3DSWAPEFFECT_DISCARD;
inline constexpr auto address_clamp=D3DTADDRESS_CLAMP;
inline constexpr auto address_wrap=D3DTADDRESS_WRAP;
inline constexpr auto filter_linear=D3DTEXF_LINEAR;
inline constexpr auto filter_point=D3DTEXF_POINT;
inline constexpr auto texture_operation_modulate=D3DTOP_MODULATE;
inline constexpr auto texture_stage_alphaop=D3DTSS_ALPHAOP;
inline constexpr auto transform_projection=D3DTS_PROJECTION;
inline constexpr auto transform_view=D3DTS_VIEW;
inline constexpr auto transform_world=D3DTS_WORLD;
inline constexpr auto usage_rendertarget=D3DUSAGE_RENDERTARGET;
inline constexpr auto ok=D3D_OK;
inline constexpr auto sdk_version=D3D_SDK_VERSION;
constexpr VertexElement declaration_end(){return D3DDECL_END();}
#endif
}
