"""Generate guarded input patches from inspect_cv4 JSON; contains no game bytecode.
Usage: python tools/generate_input_adapter.py EXTRACTED_JSON_DIRECTORY
"""
import json,sys
from pathlib import Path

def fingerprint(f):
    h=2166136261
    for ins in f['instructions']:
        for value in ins:
            for b in (value & 0xffffffff).to_bytes(4,'little'):
                h=((h^b)*16777619)&0xffffffff
    # Include string literal identities: instruction operands alone are insufficient.
    for v in f['literals']:
        if isinstance(v,str) and v.isascii():
            for b in v.encode('utf-8')+b'\0': h=((h^b)*16777619)&0xffffffff
    return h

def mapping(src,name,key,i,ins):
    menu=src.startswith('data/system/') or src.startswith('data/worldmap/')
    player=src.startswith('data/script/player')
    if key in ('x','y'): return ('menu' if menu else 'move')+key.upper()
    if key in ('b0','k0'):return 'jump' if player else 'confirm'
    if key in ('b2','k2') and player:return 'useItem'
    if key in ('b1','k1'):
        if src=='data/script/global.nut' and name=='UpdateGlobal':return 'pause'
        if src.startswith('data/worldmap/'):return 'pause'
        if '/pause/' in src and name=='Update':return 'menuBack'
    if key=='b3':
        if src=='data/script/enemy/base.nut':return 'carry'
        if player:
            if src=='data/script/player.nut' and name=='Update':
                return 'run' if ins[i+1][1]==26 else 'attack'
            return 'run'
    return None

entries={}
for p in Path(sys.argv[1]).glob('*.cv4.json'):
 def walk(f):
    src=f['source'].replace('\\','/').lower();name=f['name'] or '';ins=f['instructions'];lit=f['literals'];patches=[];writes=[]
    for i in range(1,len(ins)):
        prev=ins[i-1];cur=ins[i]
        if prev[1]!=9 or lit[prev[0]]!='input':continue
        if cur[1]==9 and cur[3]==prev[2]:
            key=lit[cur[0]];target=mapping(src,name,key,i,ins)
            if src=='data/script/stage.nut' and key=='y':
                target={'CheckDoor':'door','CheckDoorHidden':'door','CheckPipeUp':'pipeUp','CheckPipeDown':'pipeDown'}.get(name,target)
            if target:patches.append((i,target))
        if cur[1]==1:
            key=lit[cur[0]]
            # A verified assignment may include NEG before SET (ending auto-walk).
            j=i+2
            if ins[j][1]==45:j+=1
            if ins[j][1]!=13:raise ValueError((src,name,i))
            targets={'x':['moveX','menuX'],'y':['moveY','menuY','door','pipeUp','pipeDown'],
                     'b0':['jump','confirm'],'k0':['confirm'], 'b1':['pause','menuBack'],
                     'b2':['useItem'],'b3':['attack','run','carry']}.get(key,[])
            for target in targets:writes.append((j,target))
    if 'input' in lit:
        entries[(src,name,fingerprint(f))]=(patches,writes)
    for child in f['functions']:walk(child)
 walk(json.loads(p.read_text(encoding='utf-8')))
out=['// Generated by tools/generate_input_adapter.py. No original bytecode/assets.','static const Rule rules[] = {']
for (src,name,h),(patches,writes) in sorted(entries.items()):
    pp=', '.join('{%d, "%s", false}'%x for x in patches)
    ww=', '.join('{%d, "%s", true}'%x for x in writes)
    out.append('    {"%s", "%s", 0x%08xu, {%s}},'%(src,name,h,', '.join(x for x in [pp,ww] if x)))
out.append('};')
Path('src/squirrel/input_adapter_rules.inc').write_text('\n'.join(out)+'\n',encoding='utf-8')
print(len(entries),'guarded function variants')
