# This module has no dependency on the legacy Win32/x86 runtime.
set(SDL_SHARED OFF CACHE BOOL "" FORCE)
set(SDL_STATIC ON CACHE BOOL "" FORCE)
set(SDL_TEST_LIBRARY OFF CACHE BOOL "" FORCE)
set(SDL_TESTS OFF CACHE BOOL "" FORCE)
set(SDL_EXAMPLES OFF CACHE BOOL "" FORCE)
set(SDL_INSTALL OFF CACHE BOOL "" FORCE)
add_subdirectory(third_party/SDL3-3.4.16 EXCLUDE_FROM_ALL)
add_library(kinoko_platform STATIC src/platform/sdl_platform.cpp)
target_include_directories(kinoko_platform PUBLIC include)
target_link_libraries(kinoko_platform PUBLIC SDL3::SDL3-static)
target_compile_features(kinoko_platform PUBLIC cxx_std_17)
add_executable(kinoko_platform_contract tests/platform_contract.cpp)
target_link_libraries(kinoko_platform_contract PRIVATE kinoko_platform)
enable_testing()
add_test(NAME platform_contract COMMAND kinoko_platform_contract)
set_tests_properties(platform_contract PROPERTIES ENVIRONMENT "SDL_VIDEODRIVER=dummy;SDL_AUDIODRIVER=dummy" TIMEOUT 30)

add_library(kinoko_audio_output STATIC src/platform/audio_ring.cpp src/platform/sdl_audio_output.cpp)
target_include_directories(kinoko_audio_output PUBLIC include)
target_link_libraries(kinoko_audio_output PUBLIC SDL3::SDL3-static)
target_compile_features(kinoko_audio_output PUBLIC cxx_std_17)
add_executable(kinoko_audio_output_contract tests/audio_output_contract.cpp)
target_link_libraries(kinoko_audio_output_contract PRIVATE kinoko_audio_output)
add_test(NAME audio_output_contract COMMAND kinoko_audio_output_contract)
set_tests_properties(audio_output_contract PROPERTIES ENVIRONMENT "SDL_AUDIODRIVER=dummy" TIMEOUT 30)

# The semantic blend interface has no SDL/Windows dependency.
add_library(kinoko_render_state INTERFACE)
target_include_directories(kinoko_render_state INTERFACE include)
target_compile_features(kinoko_render_state INTERFACE cxx_std_17)
add_executable(kinoko_render_blend_contract tests/render_blend_contract.cpp)
target_link_libraries(kinoko_render_blend_contract PRIVATE kinoko_render_state)
add_test(NAME render_blend_contract COMMAND kinoko_render_blend_contract)

add_executable(kinoko_render_resources_contract tests/render_resources_contract.cpp)
target_link_libraries(kinoko_render_resources_contract PRIVATE kinoko_render_state)
add_test(NAME render_resources_contract COMMAND kinoko_render_resources_contract)
