# This module has no dependency on the legacy Win32/x86 runtime.
set(SDL_SHARED OFF CACHE BOOL "" FORCE)
set(SDL_STATIC ON CACHE BOOL "" FORCE)
set(SDL_TEST_LIBRARY OFF CACHE BOOL "" FORCE)
set(SDL_TESTS OFF CACHE BOOL "" FORCE)
set(SDL_EXAMPLES OFF CACHE BOOL "" FORCE)
set(SDL_INSTALL OFF CACHE BOOL "" FORCE)
# SDL GPU is the game renderer. Never build SDL's unrelated D3D9 renderer.
set(SDL_RENDER_D3D OFF CACHE BOOL "" FORCE)
add_subdirectory(third_party/SDL3-3.4.16 EXCLUDE_FROM_ALL)
target_include_directories(SDL3-static BEFORE PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/cmake/no-d3d9")
add_library(kinoko_platform STATIC src/platform/sdl_platform.cpp)
target_include_directories(kinoko_platform PUBLIC include)
target_link_libraries(kinoko_platform PUBLIC SDL3::SDL3-static)
target_compile_features(kinoko_platform PUBLIC cxx_std_17)
add_executable(kinoko_platform_contract tests/platform_contract.cpp)
target_link_libraries(kinoko_platform_contract PRIVATE kinoko_platform)
enable_testing()
add_test(NAME platform_contract COMMAND kinoko_platform_contract)
set_tests_properties(platform_contract PROPERTIES ENVIRONMENT "SDL_VIDEODRIVER=dummy;SDL_AUDIODRIVER=dummy" TIMEOUT 30)

add_library(kinoko_audio_output STATIC src/platform/audio_ring.cpp src/platform/sdl_audio_output.cpp)
target_include_directories(kinoko_audio_output PUBLIC include)
target_link_libraries(kinoko_audio_output PUBLIC SDL3::SDL3-static)
target_compile_features(kinoko_audio_output PUBLIC cxx_std_17)
add_executable(kinoko_audio_output_contract tests/audio_output_contract.cpp)
target_link_libraries(kinoko_audio_output_contract PRIVATE kinoko_audio_output)
add_test(NAME audio_output_contract COMMAND kinoko_audio_output_contract)
set_tests_properties(audio_output_contract PROPERTIES ENVIRONMENT "SDL_AUDIODRIVER=dummy" TIMEOUT 30)

# The semantic blend interface has no SDL/Windows dependency.
add_library(kinoko_render_state INTERFACE)
target_include_directories(kinoko_render_state INTERFACE include)
target_compile_features(kinoko_render_state INTERFACE cxx_std_17)
add_executable(kinoko_render_blend_contract tests/render_blend_contract.cpp)
target_link_libraries(kinoko_render_blend_contract PRIVATE kinoko_render_state)
add_test(NAME render_blend_contract COMMAND kinoko_render_blend_contract)

add_executable(kinoko_render_resources_contract tests/render_resources_contract.cpp)
target_link_libraries(kinoko_render_resources_contract PRIVATE kinoko_render_state)
add_test(NAME render_resources_contract COMMAND kinoko_render_resources_contract)

include(${CMAKE_CURRENT_LIST_DIR}/ModernGpu.cmake)

# Runtime-only graphics records and explicit listener dispatch compile on every
# portable target, including Windows x64, without original fixed-layout headers.
add_executable(kinoko_graphics_runtime_contract tests/graphics_runtime_contract.cpp)
target_include_directories(kinoko_graphics_runtime_contract PRIVATE include "${CMAKE_CURRENT_SOURCE_DIR}/cmake/no-d3d9")
target_compile_features(kinoko_graphics_runtime_contract PRIVATE cxx_std_17)
add_test(NAME graphics_runtime_contract COMMAND kinoko_graphics_runtime_contract)

# Font ownership is native-width; the ACT configuration bridge remains x86.
add_executable(kinoko_font_runtime_contract tests/font_runtime_contract.cpp)
target_include_directories(kinoko_font_runtime_contract PRIVATE include)
target_compile_features(kinoko_font_runtime_contract PRIVATE cxx_std_17)
add_test(NAME font_runtime_contract COMMAND kinoko_font_runtime_contract)
add_executable(kinoko_act_texture_runtime_contract tests/act_texture_runtime_contract.cpp
    src/reconstructed/legacy_string.cpp)
target_include_directories(kinoko_act_texture_runtime_contract PRIVATE include)
target_compile_features(kinoko_act_texture_runtime_contract PRIVATE cxx_std_17)
add_test(NAME act_texture_runtime_contract COMMAND kinoko_act_texture_runtime_contract)
add_executable(kinoko_act_chip_runtime_contract tests/act_chip_runtime_contract.cpp
    src/reconstructed/legacy_string.cpp)
target_include_directories(kinoko_act_chip_runtime_contract PRIVATE include)
target_compile_features(kinoko_act_chip_runtime_contract PRIVATE cxx_std_17)
add_test(NAME act_chip_runtime_contract COMMAND kinoko_act_chip_runtime_contract)
add_executable(kinoko_act_method_dispatch_contract tests/act_method_dispatch_contract.cpp)
target_include_directories(kinoko_act_method_dispatch_contract PRIVATE include)
target_compile_features(kinoko_act_method_dispatch_contract PRIVATE cxx_std_17)
add_test(NAME act_method_dispatch_contract COMMAND kinoko_act_method_dispatch_contract)
add_executable(kinoko_legacy_string_width_contract tests/legacy_string_width_contract.cpp)
target_include_directories(kinoko_legacy_string_width_contract PRIVATE include)
target_compile_features(kinoko_legacy_string_width_contract PRIVATE cxx_std_17)
add_test(NAME legacy_string_width_contract COMMAND kinoko_legacy_string_width_contract)
if(WIN32)
    add_library(kinoko_font_raster_compile OBJECT src/reconstructed/string_font.cpp)
    target_include_directories(kinoko_font_raster_compile PRIVATE include "${CMAKE_CURRENT_SOURCE_DIR}/cmake/no-d3d9")
    target_compile_features(kinoko_font_raster_compile PRIVATE cxx_std_17)
    add_library(kinoko_squirrel_object_width_compile OBJECT tests/squirrel_object_width_compile.cpp)
    target_include_directories(kinoko_squirrel_object_width_compile PRIVATE include
        "${CMAKE_CURRENT_SOURCE_DIR}/third_party/squirrel-2.2.2/include")
    target_compile_features(kinoko_squirrel_object_width_compile PRIVATE cxx_std_17)
    add_library(kinoko_legacy_string_width_compile OBJECT src/reconstructed/legacy_string.cpp)
    target_include_directories(kinoko_legacy_string_width_compile PRIVATE include)
    target_compile_features(kinoko_legacy_string_width_compile PRIVATE cxx_std_17)
endif()
